/**
 * @generated
 * @file AboutUsContent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import RichText from "../webflow_modules/Basic/components/RichText";
import Section from "../webflow_modules/Layout/components/Section";
import { ButtonGroup } from "../ButtonGroup";

/**
 * Props for {@link AboutUsContent}
 */
export type AboutUsContentProps = {
  /** Label for the first CTA button.*/
  buttonGroupCta1Label?: React.ReactNode;
  /** Link for the first CTA button.*/
  buttonGroupCta1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonGroupCta1Visibility?: boolean;
  /** Label text for the second CTA button.*/
  buttonGroupCta2Label?: React.ReactNode;
  /** Link for the second CTA button.*/
  buttonGroupCta2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonGroupCta2Visibility?: boolean;
  /** For text links and such.*/
  extraRichText?: React.ReactNode;
  eyebrow1?: React.ReactNode;
  eyebrow2?: React.ReactNode;
  id?: string;
  text1?: React.ReactNode;
  text2?: React.ReactNode;
};

/**
 * AboutUsContent
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function AboutUsContent({
  buttonGroupCta1Label = "Call to Action",

  buttonGroupCta1Link = {
    href: "#",
  },

  buttonGroupCta1Visibility = true,
  buttonGroupCta2Label = "Call to Action",

  buttonGroupCta2Link = {
    href: "#",
  },

  buttonGroupCta2Visibility = true,
  extraRichText = "",
  eyebrow1 = "( _Who we work with )",
  eyebrow2 = "( _Meet our team )",
  id = "work",
  text1 = "We partner with enterprise organizations and established brands that operate at scale and care about doing things the right way. Our clients typically have internal marketing, brand, or digital teams and need an experienced external partner who can step in, lead confidently, and deliver premium web experiences without constant oversight.",
  text2 = "Ria Scureman has led enterprise scale initiatives including the rollout of a global design system and high priority campaign work, and is recognized for speed, precision, and strategic thinking. Michael Napier brings deep enterprise CMS and development expertise, including component architecture, performance audits, and large scale event builds, along with advanced Webflow certification and best practices.",
}: AboutUsContentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section"}
        grid={{
          type: "section",
        }}
        id={id}
        tag={"section"}
      >
        <Block className={"container-full"} tag={"div"}>
          <Block className={"padding-global"} tag={"div"}>
            <Heading
              className={"eyebrow margin-bottom margin-xsmall"}
              tag={"h2"}
            >
              {eyebrow1}
            </Heading>
            <Paragraph className={"display-text"}>{text1}</Paragraph>
            <Block className={"spacer"} tag={"div"} />
            <Block className={"emblems-group align-center"} tag={"div"}>
              <HtmlEmbed
                className={"emblem hide-mobile-portrait"}
                content={
                  '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"emblem"}
                content={
                  '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"emblem hide-mobile-portrait"}
                content={
                  '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                }
              />
            </Block>
            <Block className={"spacer"} tag={"div"} />
            <Block className={"max-width-xlarge align-center"} tag={"div"}>
              <Heading
                className={"eyebrow margin-bottom margin-xsmall"}
                tag={"h2"}
              >
                {eyebrow2}
              </Heading>
              <Paragraph className={"margin-0"}>{text2}</Paragraph>
              <RichText
                className={"min-height-0 margin-top margin-small"}
                tag={"div"}
              >
                {extraRichText}
              </RichText>
              <Block className={"margin-top margin-xlarge"} tag={"div"}>
                <ButtonGroup
                  cta1Label={buttonGroupCta1Label}
                  cta1Link={buttonGroupCta1Link}
                  cta2Label={buttonGroupCta2Label}
                  cta2Link={buttonGroupCta2Link}
                  position={"Center"}
                  visibility={buttonGroupCta1Visibility}
                  visibility2={buttonGroupCta2Visibility}
                />
              </Block>
            </Block>
          </Block>
        </Block>
        <Block className={"spacer"} tag={"div"} />
      </Section>
    </div>
  );
}
