/**
 * @generated
 * @file ContactSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Section from "../webflow_modules/Layout/components/Section";
import { ContactForm } from "../forms/ContactForm";

/**
 * Props for {@link ContactSection}
 */
export type ContactSectionProps = {
  sectionBackground?: "Base mode" | "Dark Mode";
};

/**
 * ContactSection
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function ContactSection({
  sectionBackground = "Base mode",
}: ContactSectionProps) {
  const _styleVariantMap = {
    "Base mode": "",
    "Dark Mode": "w-variant-976a8650-6e3e-c4df-e90e-846fdaeb8253",
  };

  const _activeStyleVariant = _styleVariantMap[sectionBackground];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`section section_contact ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"contact"}
        tag={"section"}
      >
        <Block className={`container-full ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`padding-global padding-section-large ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`contact_container ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`contact_content ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`contact_content-header ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`eyebrow ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {"( _Contact )"}
                  </Block>
                  <Heading
                    className={`heading-title margin-0 ${_activeStyleVariant}`}
                    tag={"h2"}
                  >
                    {"Contact us"}
                  </Heading>
                  <Block
                    className={`heading-title text-style-muted ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {"Let's talk about your project."}
                  </Block>
                  <Block
                    className={`text-size-xlarge ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block tag={"div"}>
                      {"Use the form to send me a message"}
                    </Block>
                    <Block
                      className={`text-style-muted ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      {"or email ria@riascureman.com"}
                    </Block>
                  </Block>
                </Block>
                <Block
                  className={`emblems-group margin-top margin-medium ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <HtmlEmbed
                    className={`emblem ${_activeStyleVariant}`}
                    content={
                      '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                    }
                  />
                  <HtmlEmbed
                    className={`emblem hide-tablet ${_activeStyleVariant}`}
                    content={
                      '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                    }
                  />
                  <HtmlEmbed
                    className={`emblem hide-tablet ${_activeStyleVariant}`}
                    content={
                      '<svg xmlns="http://www.w3.org/2000/svg" width="101" height="100" viewBox="0 0 101 100" fill="none">\n  <path d="M54.2354 53.8457C78.7975 54.4766 98.9406 74.2646 99.584 98.79H54.2354V53.8457ZM46.5742 98.79H1.22559C1.869 74.2647 22.0121 54.4767 46.5742 53.8457V98.79ZM99.5996 46.1689H54.252C54.8954 21.6438 75.0378 1.85583 99.5996 1.22461V46.1689ZM1.20996 1.22461C25.7719 1.85577 45.9141 21.6438 46.5576 46.1689H1.20996V1.22461Z" stroke="currentColor" stroke-width="2.41935"/>\n</svg>'
                    }
                  />
                </Block>
              </Block>
              <Block
                className={`contact_form-wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <ContactForm
                  emailFieldLabel={"Your Email"}
                  emailFieldPlaceholder={"yourname@example.com"}
                  messageFieldLabel={"Your Message"}
                  messageFieldPlaceholder={"Type your message here"}
                  messagingErrorMessage={
                    "Oops! Something went wrong while submitting the form."
                  }
                  messagingSuccessMessage={
                    "Thank you! Your submission has been received!"
                  }
                  nameFieldLabel={"Your Name"}
                  nameFieldsFirstNamePlaceholder={"First Name"}
                  nameFieldsLastNamePlaceholder={"Last Name"}
                  submitButtonLabel={"Send Message"}
                  variant={"Base mode"}
                />
              </Block>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
