/**
 * @generated
 * @file ServicesSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";
import Section from "../webflow_modules/Layout/components/Section";
import * as _interactions from "../webflow_modules/interactions";
import { BladeHeaderContent } from "../BladeHeaderContent";

const _interactionsData = JSON.parse(
  '{"events":{"e-35":{"id":"e-35","name":"","animationType":"custom","eventTypeId":"SCROLL_INTO_VIEW","action":{"id":"","actionTypeId":"GENERAL_START_ACTION","config":{"delay":0,"easing":"","duration":0,"actionListId":"a-10","affectedElements":{},"playInReverse":false,"autoStopEventId":"e-36"}},"mediaQueries":["main","medium","small","tiny"],"target":{"id":"34344561-8005-4dbb-c933-c756b481f129","appliesTo":"ELEMENT","styleBlockIds":[]},"targets":[{"id":"34344561-8005-4dbb-c933-c756b481f129","appliesTo":"ELEMENT","styleBlockIds":[]}],"config":{"loop":false,"playInReverse":false,"scrollOffsetValue":10,"scrollOffsetUnit":"%","delay":null,"direction":null,"effectIn":null},"createdOn":1779558783252}},"actionLists":{"a-10":{"id":"a-10","title":"Fade In Up","actionItemGroups":[{"actionItems":[{"id":"a-10-n","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":true,"id":"6977aaebd7dce4044b372051|ffe55596-5cd7-3f02-e6e7-d2895b2c3049"},"yValue":60,"xUnit":"PX","yUnit":"px","zUnit":"PX"}},{"id":"a-10-n-3","actionTypeId":"STYLE_OPACITY","config":{"delay":0,"easing":"","duration":500,"target":{"useEventTarget":true,"id":"6977aaebd7dce4044b372051|ffe55596-5cd7-3f02-e6e7-d2895b2c3049"},"value":0,"unit":""}}]},{"actionItems":[{"id":"a-10-n-2","actionTypeId":"TRANSFORM_MOVE","config":{"delay":0,"easing":[0,0,0,1],"duration":260,"target":{"useEventTarget":true,"id":"6977aaebd7dce4044b372051|ffe55596-5cd7-3f02-e6e7-d2895b2c3049"},"yValue":0,"xUnit":"PX","yUnit":"px","zUnit":"PX"}},{"id":"a-10-n-4","actionTypeId":"STYLE_OPACITY","config":{"delay":120,"easing":"","duration":260,"target":{"useEventTarget":true,"id":"6977aaebd7dce4044b372051|ffe55596-5cd7-3f02-e6e7-d2895b2c3049"},"value":1,"unit":""}}]}],"useFirstGroupAsInitialState":true,"createdOn":1774623094870}},"site":{"mediaQueries":[{"key":"main","min":992,"max":10000},{"key":"medium","min":768,"max":991},{"key":"small","min":480,"max":767},{"key":"tiny","min":0,"max":479}]}}'
);

/**
 * Props for {@link ServicesSection}
 */
export type ServicesSectionProps = {
  accordionItemSlot?: React.ReactNode;
  backgroundColor?: string;
  /** Label for the first CTA button.*/
  bladeHeaderContentCta1Label?: React.ReactNode;
  /** Link for the first CTA button.*/
  bladeHeaderContentCta1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Label text for the second CTA button.*/
  bladeHeaderContentCta2Label?: React.ReactNode;
  /** Link for the second CTA button.*/
  bladeHeaderContentCta2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Eyebrow text (alt font)*/
  bladeHeaderContentEyebrow?: React.ReactNode;
  bladeHeaderContentText?: React.ReactNode;
  /** Blade title text*/
  bladeHeaderContentTitle?: React.ReactNode;
  variant?: "Base mode" | "Dark Mode";
};

/**
 * ServicesSection
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function ServicesSection({
  accordionItemSlot,
  backgroundColor = "purple",
  bladeHeaderContentCta1Label = "Call to Action",

  bladeHeaderContentCta1Link = {
    href: "#",
  },

  bladeHeaderContentCta2Label = "Call to Action",

  bladeHeaderContentCta2Link = {
    href: "#",
  },

  bladeHeaderContentEyebrow = "( _Eyebrow )",
  bladeHeaderContentText = "Blade header description text.",
  bladeHeaderContentTitle = "Blade Header Title",
  variant = "Base mode",
}: ServicesSectionProps) {
  _interactions.useInteractions(_interactionsData);

  const _styleVariantMap = {
    "Base mode": "",
    "Dark Mode": "w-variant-d442aba8-2053-b4fe-f046-65ae1c277cc3",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`section section_services w-node-_34344561-8005-4dbb-c933-c756b481f129-b481f129 ${backgroundColor} ${_activeStyleVariant}`}
        data-w-id={"34344561-8005-4dbb-c933-c756b481f129"}
        grid={{
          type: "section",
        }}
        id={"services"}
        tag={"section"}
      >
        <Block className={`container-full ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`padding-global ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`services_wrapper ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`sevices_header ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`services_header-media flex-1-desktop ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Image
                    alt={
                      "Artistic collage of website designs featuring a skier hero image, Lenovo campaigns, and multiple modern homepage layouts."
                    }
                    className={`services_header-image ${_activeStyleVariant}`}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/69244a514e5720feec5d3ba9/698b4ce28b59e878f0e71fbc_services-blade-image.avif"
                    }
                    width={"auto"}
                  />
                </Block>
                <Block
                  className={`services_header-content flex-1-desktop ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <BladeHeaderContent
                    cta1Label={bladeHeaderContentCta1Label}
                    cta1Link={bladeHeaderContentCta1Link}
                    cta2Label={bladeHeaderContentCta2Label}
                    cta2Link={bladeHeaderContentCta2Link}
                    eyebrow={bladeHeaderContentEyebrow}
                    text={bladeHeaderContentText}
                    title={bladeHeaderContentTitle}
                    variant={"Dark Mode"}
                  />
                </Block>
              </Block>
              <Block
                className={`spacer-xhuge ${_activeStyleVariant}`}
                tag={"div"}
              />
              <Block
                className={`services_accordion-wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`accordion ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {accordionItemSlot}
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
      </Section>
    </div>
  );
}
