/**
 * @generated
 * @file TeamMemberBio (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";
import RichText from "../webflow_modules/Basic/components/RichText";

/**
 * Props for {@link TeamMemberBio}
 */
export type TeamMemberBioProps = {
  /** Either "radius-md-top-left" or "radius-md-top-right" for curve location on portrait backgroun.*/
  backgroundType?: string;
  badge?: string;
  badgeLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  bioFirstHalf?: React.ReactNode;
  bioSecondHalf?: React.ReactNode;
  /** Element ID for anchor linking*/
  id?: string;
  name?: React.ReactNode;
  portrait?: string;
  quote?: React.ReactNode;
  role?: React.ReactNode;
  variant?: "Quote On Right" | "Quote On Left";
};

/**
 * TeamMemberBio
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function TeamMemberBio({
  backgroundType = "",
  badge = "",

  badgeLink = {
    href: "#",
  },

  bioFirstHalf = "",
  bioSecondHalf = "",
  id = "",
  name = "Team Member",
  portrait = "https://cdn.prod.website-files.com/69244a514e5720feec5d3ba9/69a1be86287a0898630fd387_rsd-about-bio-ria-scureman.avif",
  quote = "This is the special quote.",
  role = "( _Founder / Designer, Creative Director )",
  variant = "Quote On Right",
}: TeamMemberBioProps) {
  const _styleVariantMap = {
    "Quote On Right": "",
    "Quote On Left": "w-variant-ecc83593-abf9-eb75-b237-ab1fac50c4c7",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`team_member-container padding-section-medium ${_activeStyleVariant}`}
        id={id}
        tag={"div"}
      >
        <Block
          className={`team_member-intro ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Block
            className={`team_member-portrait ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`team_member-portrait_background ${backgroundType} ${_activeStyleVariant}`}
              tag={"div"}
            />
            <Image
              alt={""}
              className={`team_member-portrait_image ${_activeStyleVariant}`}
              height={"auto"}
              loading={"lazy"}
              src={portrait}
              width={"auto"}
            />
          </Block>
          <Block
            className={`team_member-title ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Heading
              className={`text-size-display-sm text-weight-medium ${_activeStyleVariant}`}
              tag={"h3"}
            >
              {name}
            </Heading>
            <Block className={`eyebrow ${_activeStyleVariant}`} tag={"div"}>
              {role}
            </Block>
          </Block>
        </Block>
        <Block className={`team_member-bio ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`team_member-bio_text ${_activeStyleVariant}`}
            tag={"div"}
          >
            <RichText
              className={`text-size-xlarge ${_activeStyleVariant}`}
              tag={"div"}
            >
              {bioFirstHalf}
            </RichText>
            <Block
              className={`team_member-quote_mobile ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block className={`flex-row ${_activeStyleVariant}`} tag={"div"}>
                <Block
                  className={`text-size-display-3xl text-color-purple text-weight-semibold ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {"“"}
                </Block>
                <Block
                  className={`text-size-display-md text-weight-medium text-color-purple padding-xsmall ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {quote}
                </Block>
              </Block>
              <Link
                block={"inline"}
                button={false}
                className={`align-center ${_activeStyleVariant}`}
                options={badgeLink}
              >
                {badge.trim() !== "" ? (
                  <Image
                    alt={""}
                    className={`team_member-badge align-center ${_activeStyleVariant}`}
                    height={"auto"}
                    loading={"lazy"}
                    src={badge}
                    width={"auto"}
                  />
                ) : null}
              </Link>
            </Block>
            <RichText
              className={`text-size-xlarge ${_activeStyleVariant}`}
              tag={"div"}
            >
              {bioSecondHalf}
            </RichText>
          </Block>
          <Block
            className={`team_member-quote hide-tablet ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`text-size-display-3xl text-color-purple text-weight-semibold ${_activeStyleVariant}`}
              tag={"div"}
            >
              {"“"}
            </Block>
            <Block className={`flex-column ${_activeStyleVariant}`} tag={"div"}>
              <Block
                className={`padding-small text-size-display-md text-weight-medium text-color-purple ${_activeStyleVariant}`}
                tag={"div"}
              >
                {quote}
              </Block>
              <Link
                block={"inline"}
                button={false}
                className={`align-center ${_activeStyleVariant}`}
                options={badgeLink}
              >
                {badge.trim() !== "" ? (
                  <Image
                    alt={""}
                    className={`team_member-badge align-center ${_activeStyleVariant}`}
                    height={"auto"}
                    loading={"lazy"}
                    src={badge}
                    width={"auto"}
                  />
                ) : null}
              </Link>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
