/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

// import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Link from "next/link";
import style from "./button.module.css";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {
  /** Label for the button.*/
  ctaLabel?: React.ReactNode;
  /** Link for the button.*/
  ctaLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Styling for the button. */
  ctaStyle?: {
    style?: "primary" | "secondary";
    type?: "link" | "button";
  };
  /** ARIA label string for accessibility. */
  ctaAria?: string;
};

/**
 * Call-to-action component that can be styled as a button or a link.
 */
export default function Button({
  ctaLabel = "Call to Action",

  ctaLink = {
    href: "#",
  },

  ctaStyle = { type: "button", style: "primary" },
  ctaAria = ctaLabel as string,
}: ButtonProps) {
  return (
    <Link 
      className={`${style.cta} ${(ctaStyle.type === "button" || !ctaStyle.type) ? style.button : ''} ${ctaStyle.style === "secondary" ? style.isSecondary : ''}`}
      href={ctaLink.href}
      target={ctaLink.target}
      aria-label={ctaAria}
    >
      {ctaLabel}
    </Link>
  );
}
