/**
 * @generated
 * @file CmsImageVideo (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";

/**
 * Props for {@link CmsImageVideo}
 */
export type CmsImageVideoProps = {
  galleryVideoFrame?: string;
  imageField?: string;
  /** Sets the ID for the video element.*/
  videoElementId?: string;
  videoField?: string;
};

/**
 * CmsImageVideo
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function CmsImageVideo({
  galleryVideoFrame = "",
  imageField = "",
  videoElementId = "",
  videoField = "",
}: CmsImageVideoProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"cms-image-video"} tag={"div"}>
        <HtmlEmbed
          className={"cms-video"}
          content={
            '<video autoplay muted playsinline class="fit-cover">\n</video>'
          }
          id={videoElementId}
          // @ts-ignore - User-defined custom attribute(s)
          videoframe={galleryVideoFrame}
          videourl={videoField}
        />
        <Image
          alt={""}
          className={"cms-image"}
          height={"Auto"}
          loading={"lazy"}
          src={imageField}
          width={"Auto"}
        />
      </Block>
    </div>
  );
}
