/**
 * @generated
 * @file BladeHeaderContent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import { ButtonGroup } from "./ButtonGroup";
import { toText } from "./webflow_modules/ListOfElements/helpers/toText";

/**
 * Props for {@link BladeHeaderContent}
 */
export type BladeHeaderContentProps = {
  /** Label for the first CTA button.*/
  cta1Label?: React.ReactNode;
  /** Link for the first CTA button.*/
  cta1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Label text for the second CTA button.*/
  cta2Label?: React.ReactNode;
  /** Link for the second CTA button.*/
  cta2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Eyebrow text (alt font)*/
  eyebrow?: React.ReactNode;
  text?: React.ReactNode;
  /** Blade title text*/
  title?: React.ReactNode;
  variant?: "Base" | "Dark Mode";
};

/**
 * BladeHeaderContent
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function BladeHeaderContent({
  cta1Label = "Call to Action",

  cta1Link = {
    href: "#",
  },

  cta2Label = "Call to Action",

  cta2Link = {
    href: "#",
  },

  eyebrow = "( _Eyebrow )",
  text = "Blade header copy description text.",
  title = "Blade title text",
  variant = "Base",
}: BladeHeaderContentProps) {
  const _styleVariantMap = {
    Base: "",
    "Dark Mode": "w-variant-43a7f0b1-10ce-2552-e311-4fbf596b46fd",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`header-content  ${_activeStyleVariant}`} tag={"div"}>
        <Block className={`header-text ${_activeStyleVariant}`} tag={"div"}>
          <Block className={`eyebrow ${_activeStyleVariant}`} tag={"div"}>
            {eyebrow}
          </Block>
          <Heading
            className={`heading-title ${_activeStyleVariant}`}
            tag={"h2"}
          >
            {title}
          </Heading>
          <Paragraph
            className={`heading-content margin-0 ${_activeStyleVariant}`}
          >
            {text}
          </Paragraph>
        </Block>
        {!!toText(cta1Label) || !!toText(cta2Label) ? (
          <Block
            className={`spacer-large ${_activeStyleVariant}`}
            tag={"div"}
          />
        ) : null}
        <ButtonGroup
          cta1Label={cta1Label}
          cta1Link={cta1Link}
          cta2Label={cta2Label}
          cta2Link={cta2Link}
          visibility={!toText(cta1Label) ? false : true}
          visibility2={!toText(cta2Label) ? false : true}
        />
      </Block>
    </div>
  );
}
