/**
 * @generated
 * @file ButtonGroup (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtonGroup}
 *
 * Two CTAs
 */
export type ButtonGroupProps = {
  /** Label for the first CTA button.*/
  cta1Label?: React.ReactNode;
  /** Link for the first CTA button.*/
  cta1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** Label text for the second CTA button.*/
  cta2Label?: React.ReactNode;
  /** Link for the second CTA button.*/
  cta2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  position?: "Left" | "Center";
  visibility?: boolean;
  visibility2?: boolean;
};

/**
 * ButtonGroup
 *
 * Two CTAs
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function ButtonGroup({
  cta1Label = "Call to Action",

  cta1Link = {
    href: "#",
  },

  cta2Label = "Call to Action",

  cta2Link = {
    href: "#",
  },

  position = "Left",
  visibility = true,
  visibility2 = true,
}: ButtonGroupProps) {
  const _styleVariantMap = {
    Left: "",
    Center: "w-variant-ded3d468-0d44-8038-9f9e-f6956af14143",
  };

  const _activeStyleVariant = _styleVariantMap[position];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`button-group ${_activeStyleVariant}`} tag={"div"}>
        {visibility ? (
          <Link
            button={true}
            className={`button ${_activeStyleVariant}`}
            options={cta1Link}
          >
            {cta1Label}
          </Link>
        ) : null}
        {visibility2 ? (
          <Link
            button={true}
            className={`button is-secondary ${_activeStyleVariant}`}
            options={cta2Link}
          >
            {cta2Label}
          </Link>
        ) : null}
      </Block>
    </div>
  );
}
