/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {
  /** Label for the first CTA button.*/
  cta1Label?: React.ReactNode;
  /** Link for the first CTA button.*/
  cta1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  variant?: "Base" | "Dark Mode";
};

/**
 * Button
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export default function Button({
  cta1Label = "Call to Action",

  cta1Link = {
    href: "#",
  },

  variant = "Base",
}: ButtonProps) {
  const _styleVariantMap = {
    Base: "",
    "Dark Mode": "w-variant-309ad327-90de-baff-17b8-c48193b7e122",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        button={true}
        className={`button ${_activeStyleVariant}`}
        options={cta1Link}
      >
        {cta1Label}
      </Link>
    </div>
  );
}
