/**
 * @generated
 * @file SeoContainer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Props for {@link SeoContainer}
 */
export type SeoContainerProps = {
  text?: React.ReactNode;
  variant?: "Base" | "Dark Mode";
};

/**
 * SeoContainer
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function SeoContainer({
  text = "This is some text inside of a div block.",
  variant = "Base",
}: SeoContainerProps) {
  const _styleVariantMap = {
    Base: "",
    "Dark Mode": "w-variant-7c430064-63ea-e9e5-631f-d507993f3023",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`seo_container ${_activeStyleVariant}`} tag={"div"}>
        <Block className={`spacer-text ${_activeStyleVariant}`} tag={"div"} />
        <Block
          className={`seo_copy align-center max-width-3xlarge ${_activeStyleVariant}`}
          tag={"div"}
        >
          {text}
        </Block>
      </Block>
    </div>
  );
}
