/**
 * @generated
 * @file FooterLinkList (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link FooterLinkList}
 */
export type FooterLinkListProps = {
  footerLinkList?: React.ReactNode;
};

/**
 * FooterLinkList
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function FooterLinkList({ footerLinkList }: FooterLinkListProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"footer_links text-align-center"} tag={"div"}>
        {footerLinkList}
      </Block>
    </div>
  );
}
