/**
 * @generated
 * @file FooterLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link FooterLink}
 */
export type FooterLinkProps = {
  label?: React.ReactNode;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
};

/**
 * FooterLink
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function FooterLink({
  label = "Footer Link",

  link = {
    href: "#",
  },
}: FooterLinkProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"footer_link"}
        options={link}
      >
        <Block className={"text-style-alt text-size-small"} tag={"div"}>
          {label}
        </Block>
      </Link>
    </div>
  );
}
