/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link Footer}
 */
export type FooterProps = {
  variant?: "Base" | "Dark Mode";
};

/**
 * Footer
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function Footer({ variant = "Base" }: FooterProps) {
  const _styleVariantMap = {
    Base: "",
    "Dark Mode": "w-variant-3e3ac7de-30a5-7e35-ae23-c9823a8e3eb0",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`footer_component  ${_activeStyleVariant}`}
        tag={"footer"}
      >
        <Block className={`container-full ${_activeStyleVariant}`} tag={"div"}>
          <Block
            className={`padding-global ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`footer_container ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`footer_wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`footer_copyright ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`text-style-alt ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {
                      "Copyright © 2026 Ria Scureman Designs. All rights reserved."
                    }
                  </Block>
                </Block>
                <Block
                  className={`footer_links ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`footer_link-list text-align-center ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "/",
                      }}
                    >
                      <Block
                        className={`text-style-alt text-size-small ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        {"Index"}
                      </Block>
                    </Link>
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "/about",
                      }}
                    >
                      <Block
                        className={`text-style-alt text-size-small ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        {"About"}
                      </Block>
                    </Link>
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "/#services",
                      }}
                    >
                      <Block
                        className={`text-style-alt text-size-small ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        {"Services"}
                      </Block>
                    </Link>
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "/work",
                      }}
                    >
                      <Block
                        className={`text-style-alt text-size-small ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        {"Work"}
                      </Block>
                    </Link>
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "#c5838762-533d-bb61-35d4-ef667b13066e",
                      }}
                    >
                      <Block
                        className={`text-style-alt text-size-small ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        {"Contact"}
                      </Block>
                    </Link>
                    <Link
                      block={"inline"}
                      button={false}
                      className={`footer_link ${_activeStyleVariant}`}
                      options={{
                        href: "https://www.linkedin.com/company/ria-scureman-designs/",
                        target: "_blank",
                      }}
                    >
                      <HtmlEmbed
                        content={
                          '<svg width="16" height="16" viewBox="0 0 120 112" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M28.9485 13.5372C28.9485 21.0136 22.4681 27.0744 14.4742 27.0744C6.48033 27.0744 0 21.0136 0 13.5372C0 6.06081 6.48033 0 14.4742 0C22.4681 0 28.9485 6.06081 28.9485 13.5372Z" fill="currentColor"/>\n<path d="M1.97938 37.0248H26.7216V112H1.97938V37.0248Z" fill="currentColor"/>\n<path d="M66.5567 37.0248H41.8144V112H66.5567C66.5567 112 66.5567 88.3967 66.5567 73.6389C66.5567 64.7809 69.5813 55.8843 81.6495 55.8843C95.2881 55.8843 95.206 67.4763 95.1424 76.4567C95.0593 88.1955 95.2577 100.175 95.2577 112H120V72.4298C119.79 47.163 113.207 35.5207 91.5464 35.5207C78.6832 35.5207 70.7097 41.3605 66.5567 46.6439V37.0248Z" fill="currentColor"/>\n</svg>'
                        }
                      />
                    </Link>
                  </Block>
                </Block>
              </Block>
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
