/**
 * @generated
 * @file Accordion (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link Accordion}
 */
export type AccordionProps = {
  accordionItemSlot?: React.ReactNode;
  variant?: "Base" | "Dark Mode";
};

/**
 * Accordion
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function Accordion({
  accordionItemSlot,
  variant = "Base",
}: AccordionProps) {
  const _styleVariantMap = {
    Base: "",
    "Dark Mode": "w-variant-60947264-94ef-4541-66a7-8a4c084e0276",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`accordion ${_activeStyleVariant}`}
        id={"w-node-e6ebdf7f-e164-ddea-1b6a-2dea15c944ff-15c944ff"}
        tag={"div"}
      >
        {accordionItemSlot}
      </Block>
    </div>
  );
}
