/**
 * @generated
 * @file ContactForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import FormButton from "../webflow_modules/Form/components/FormButton";
import FormErrorMessage from "../webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../webflow_modules/Form/components/FormSuccessMessage";
import FormWrapper from "../webflow_modules/Form/components/FormWrapper";
import { InputField } from "./InputField";
import { NameFields } from "./NameFields";
import { TextAreaField } from "./TextAreaField";

/**
 * Props for {@link ContactForm}
 */
export type ContactFormProps = {
  emailFieldLabel?: React.ReactNode;
  emailFieldPlaceholder?: string;
  messageFieldLabel?: React.ReactNode;
  messageFieldPlaceholder?: string;
  /** Message displayed with an unsuccessful form submission.*/
  messagingErrorMessage?: React.ReactNode;
  /** Message displayed with a successful form submission.*/
  messagingSuccessMessage?: React.ReactNode;
  nameFieldLabel?: React.ReactNode;
  nameFieldsFirstNamePlaceholder?: string;
  nameFieldsLastNamePlaceholder?: string;
  submitButtonLabel?: string;
  variant?: "Base mode" | "Dark Mode";
};

/**
 * ContactForm
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function ContactForm({
  emailFieldLabel = "Your Email",
  emailFieldPlaceholder = "yourname@example.com",
  messageFieldLabel = "Your Message",
  messageFieldPlaceholder = "Type your message here",
  messagingErrorMessage = "Oops! Something went wrong while submitting the form.",
  messagingSuccessMessage = "Thank you! Your submission has been received!",
  nameFieldLabel = "Your Name",
  nameFieldsFirstNamePlaceholder = "First Name",
  nameFieldsLastNamePlaceholder = "Last Name",
  submitButtonLabel = "Send Message",
  variant = "Base mode",
}: ContactFormProps) {
  const _styleVariantMap = {
    "Base mode": "",
    "Dark Mode": "w-variant-a36d0dc3-85db-8c53-5c5a-8bb2cc6efdd4",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormWrapper className={`contact-form_component ${_activeStyleVariant}`}>
        <FormForm
          // @ts-ignore - User-defined custom attribute(s)
          action={"https://usebasin.com/f/c97b458906e1"}
          className={`contact-form ${_activeStyleVariant}`}
          data-basin-form={"true"}
          data-basin-spam-protection={"recaptcha-v3"}
          data-basin-success-action={"render"}
          data-name={"Contact Form"}
          id={"wf-form-Contact-Form"}
          method={"POST"}
          name={"wf-form-Contact-Form"}
        >
          <Block
            className={`contact-form_fields ${_activeStyleVariant}`}
            tag={"div"}
          >
            <NameFields
              firstNamePlaceholder={nameFieldsFirstNamePlaceholder}
              lastNamePlaceholder={"Last Name"}
              nameFieldsLabel={"Your Name"}
            />
            <Block
              className={`contact-form_email ${_activeStyleVariant}`}
              tag={"div"}
            >
              <InputField
                fieldId={"email"}
                fieldLabel={emailFieldLabel}
                fieldName={"Email"}
                fieldPlaceholderText={emailFieldPlaceholder}
                required={"required"}
              />
            </Block>
            <TextAreaField
              fieldId={"message"}
              fieldLabel={messageFieldLabel}
              fieldName={"Message"}
              fieldPlaceholderText={messageFieldPlaceholder}
              required={"required"}
            />
            <DOM
              id={"g-recaptcha-response"}
              name={"g-recaptcha-response"}
              tag={"input"}
              type={"hidden"}
            />
            <DOM
              name={"g-recaptcha-version"}
              tag={"input"}
              type={"hidden"}
              value={"v3"}
            />
            <Block className={`spacer-0 ${_activeStyleVariant}`} tag={"div"} />
            <FormButton
              className={`button ${_activeStyleVariant}`}
              data-wait={"Please wait..."}
              type={"submit"}
              value={submitButtonLabel}
            />
          </Block>
        </FormForm>
        <FormSuccessMessage
          className={`contact-form_success-wrap ${_activeStyleVariant}`}
        >
          <Block
            className={`contact-form_success ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block tag={"div"}>{messagingSuccessMessage}</Block>
          </Block>
        </FormSuccessMessage>
        <FormErrorMessage>
          <Block tag={"div"}>{messagingErrorMessage}</Block>
        </FormErrorMessage>
      </FormWrapper>
    </div>
  );
}
