/**
 * @generated
 * @file InputField (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Props for {@link InputField}
 */
export type InputFieldProps = {
  /** ID of the input field.*/
  fieldId?: string;
  /** Text for the label of the input field.*/
  fieldLabel?: React.ReactNode;
  /** The name of the input field.*/
  fieldName?: string;
  /** Placeholder text that appears in the input field.*/
  fieldPlaceholderText?: string;
  /** Enter "required" if this field requires a value.*/
  required?: string;
  requiredFieldIcon?: React.ReactNode;
};

/**
 * InputField
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function InputField({
  fieldId = "text-field-id",
  fieldLabel = "Text Field Label",
  fieldName = "Field Name",
  fieldPlaceholderText = "Placeholder Text",
  required = "",
  requiredFieldIcon = "*",
}: InputFieldProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"form_input-wrap"} htmlFor={fieldId} tag={"label"}>
        <DOM className={"form_field-label_wrapper"} tag={"span"}>
          <Block className={"form_field-label"} tag={"div"}>
            {fieldLabel}
          </Block>
          <Block className={"form_field-label_required"} tag={"div"}>
            {requiredFieldIcon}
          </Block>
        </DOM>
        <DOM
          className={"form_input"}
          id={fieldId}
          name={fieldName}
          placeholder={fieldPlaceholderText}
          required={required}
          tag={"input"}
        />
      </DOM>
    </div>
  );
}
