/**
 * @generated
 * @file NameFields (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import { InputField } from "./InputField";

/**
 * Props for {@link NameFields}
 */
export type NameFieldsProps = {
  firstNamePlaceholder?: string;
  /** Placeholder text that appears in the input field.*/
  lastNamePlaceholder?: string;
  /** Text for the label of the input field.*/
  nameFieldsLabel?: React.ReactNode;
};

/**
 * NameFields
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function NameFields({
  firstNamePlaceholder = "First Name",
  lastNamePlaceholder = "Last Name",
  nameFieldsLabel = "Your Name",
}: NameFieldsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"form_name"} tag={"fieldset"}>
        <DOM className={"legend"} tag={"legend"}>
          {"Your Name"}
        </DOM>
        <Block className={"form_name-fields"} tag={"div"}>
          <InputField
            fieldId={"first-name"}
            fieldLabel={nameFieldsLabel}
            fieldName={"First Name"}
            fieldPlaceholderText={firstNamePlaceholder}
            required={"required"}
            requiredFieldIcon={"*"}
          />
          <InputField
            fieldId={"last-name"}
            fieldLabel={""}
            fieldName={"Last Name"}
            fieldPlaceholderText={lastNamePlaceholder}
            required={"required"}
            requiredFieldIcon={""}
          />
        </Block>
      </DOM>
    </div>
  );
}
