/**
 * @generated
 * @file Radio (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Props for {@link Radio}
 */
export type RadioProps = {};

/**
 * Radio
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function Radio({}: RadioProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"radio_label"} tag={"label"}>
        <DOM
          className={"radio_input"}
          name={"color"}
          tag={"input"}
          type={"radio"}
          value={"Red"}
        />
        <DOM className={"radio_circle_wrap"} tag={"span"}>
          <DOM className={"radio_circle_inner"} tag={"span"} />
        </DOM>
        <DOM className={"radio_text"} tag={"span"}>
          {"Red"}
        </DOM>
      </DOM>
    </div>
  );
}
