/**
 * @generated
 * @file RadioListField (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import DOM from "../webflow_modules/Builtin/components/DOM";
import List from "../webflow_modules/Basic/components/List";
import ListItem from "../webflow_modules/Basic/components/ListItem";
import { Radio } from "./Radio";

/**
 * Props for {@link RadioListField}
 */
export type RadioListFieldProps = {};

/**
 * RadioListField
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function RadioListField({}: RadioListFieldProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"radio_fieldset"} tag={"fieldset"}>
        <DOM className={"radio_legend"} tag={"legend"}>
          {"Choose a color"}
        </DOM>
        <List className={"radio_list"} tag={"ul"} unstyled={false}>
          <ListItem className={"radio_item"}>
            <Radio />
          </ListItem>
          <ListItem className={"radio_item"}>
            <DOM className={"radio_label"} tag={"label"}>
              <DOM
                checked={true}
                className={"radio_input"}
                name={"color"}
                tag={"input"}
                type={"radio"}
                value={"Green"}
              />
              <DOM className={"radio_circle_wrap"} tag={"span"}>
                <DOM className={"radio_circle_inner"} tag={"span"} />
              </DOM>
              <DOM className={"radio_text"} tag={"span"}>
                {"Green"}
              </DOM>
            </DOM>
          </ListItem>
          <ListItem className={"radio_item"}>
            <DOM className={"radio_label"} tag={"label"}>
              <DOM
                className={"radio_input"}
                name={"color"}
                tag={"input"}
                type={"radio"}
                value={"Blue"}
              />
              <DOM className={"radio_circle_wrap"} tag={"span"}>
                <DOM className={"radio_circle_inner"} tag={"span"} />
              </DOM>
              <DOM className={"radio_text"} tag={"span"}>
                {"Blue"}
              </DOM>
            </DOM>
          </ListItem>
        </List>
      </DOM>
    </div>
  );
}
