/**
 * @generated
 * @file TextAreaField (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";

/**
 * Props for {@link TextAreaField}
 */
export type TextAreaFieldProps = {
  fieldId?: string;
  fieldLabel?: React.ReactNode;
  fieldName?: string;
  fieldPlaceholderText?: string;
  /** Enter "required" if this field requires a value.*/
  required?: string;
  requiredIcon?: React.ReactNode;
};

/**
 * TextAreaField
 *
 * @see {@link https://ria-scureman-designs.design.webflow.com | Source site in Webflow}
 */
export function TextAreaField({
  fieldId = "text-field-id",
  fieldLabel = "Text Field Label",
  fieldName = "Field Name",
  fieldPlaceholderText = "Placeholder Text",
  required = "",
  requiredIcon = "*",
}: TextAreaFieldProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <DOM className={"form_textarea-wrap"} htmlFor={fieldId} tag={"label"}>
        <DOM className={"form_field-label_wrapper"} tag={"span"}>
          <Block className={"form_field-label"} tag={"div"}>
            {fieldLabel}
          </Block>
          <Block className={"form_field-label_required"} tag={"div"}>
            {requiredIcon}
          </Block>
        </DOM>
        <DOM
          className={"form_input is-text-area"}
          id={fieldId}
          name={fieldName}
          placeholder={fieldPlaceholderText}
          required={required}
          tag={"textarea"}
          type={"text"}
        />
      </DOM>
    </div>
  );
}
